/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Astronau({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/assets/astronaughtWave.glb"
  );
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions.wave.play();
  });
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      position={[3.8, -1.5, 1.5]}
      rotation={[-0.2, -1, 0]}
      receiveShadow
    >
      <group name="Scene">
        <group
          name="Sketchfab_model001"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.31}
        >
          <group name="root001">
            <group name="GLTF_SceneRootNode001" rotation={[Math.PI / 2, 0, 0]}>
              <group name="RootNode0_0" scale={0.01}>
                <group name="skeletal3_6">
                  <group name="GLTF_created_0">
                    <group name="_3_correction">
                      <group name="_3" />
                    </group>
                    <group name="_4_correction">
                      <group name="_4" />
                    </group>
                    <group name="_5_correction">
                      <group name="_5" />
                    </group>
                    <primitive object={nodes.GLTF_created_0_rootJoint} />
                    <skinnedMesh
                      name="Object_100"
                      geometry={nodes.Object_100.geometry}
                      material={materials["material_0.001"]}
                      skeleton={nodes.Object_100.skeleton}
                    />
                    <skinnedMesh
                      name="Object_103"
                      geometry={nodes.Object_103.geometry}
                      material={materials["material_1.001"]}
                      skeleton={nodes.Object_103.skeleton}
                    />
                    <skinnedMesh
                      name="Object_106"
                      geometry={nodes.Object_106.geometry}
                      material={materials["material_2.001"]}
                      skeleton={nodes.Object_106.skeleton}
                    />
                    <skinnedMesh
                      name="Object_99"
                      geometry={nodes.Object_99.geometry}
                      material={materials["material_0.001"]}
                      skeleton={nodes.Object_99.skeleton}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/assets/astronaughtWave.glb");
